image: node:latest
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
pages:
  script:
    - npm install
    - npm run-script build
    - mkdir public
    - mv build/* public
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master
